### ISSUE TITLE
to fix: bug related to a `dart.js` package imported no matter the platform the app is running on.

### ISSUE THREAD

**Issue by AmanMenda** [kkiapay/kkiapay-flutter-sdk#40]
**Bug description**
First, there are some variables a new user can't have access to. And by that i mean "nColorPrimary", "SuccessPage". It would be great if the example was really standalone.

The second thing is that whether the app is compiled on mobile/web, a dart.js package is imported, which causes the app to crash on mobile.

**To Reproduce**
Initialize a new flutter project, install the kkiapay_flutter_sdk and just copy and paste the example.

**Expected behavior**
Building the example should immediately give an overview of how the project work.

**Smartphone details:**
 - Device: Pixel 6a API 24
 - OS: Android
 
**Additional context**
N/A

**Comment by Shek863** [comment]
@AmanMenda what version are you using? 
This problem is currently in prerelease ( not recommended ) version and will be fixed

Make sure you use the latest official version kkiapay_flutter_sdk: ^1.2.12.

**Comment by AmanMenda** [comment]
Hello Shegun ! J'utilise effectivement la toute dernière version. Après avoir tenté d'installer la dépendance avec `pub`, j'ai directement mis un URL vers ton repo github pour être sûr d'avoir littéralement ton dernier push. Le problème vient du fait que tu utilises dart.js et des modules web même quand on lance sur mobile. Nous avons pu le régler en ajoutant une condition sur les modules web. On peut te laisser une PR pour que tu vois si possible.
________________________________
De : Shegun MONTCHO ***@***.***>
Envoyé : mercredi 29 mai 2024 12:16
À : kkiapay/kkiapay-flutter-sdk ***@***.***>
Cc : Aman Ilaidama MENDA ***@***.***>; Mention ***@***.***>
Objet : Re: [kkiapay/kkiapay-flutter-sdk] to fix: bug related to a `dart.js` package imported no matter the platform the app is running on. (Issue #40)


@AmanMenda<https://github.com/AmanMenda> what version are you using?
This problem is currently in prerelease ( not recommended ) version and will be fixed

Make sure you use the latest official version kkiapay_flutter_sdk: ^1.2.12.
